# places_data.py

places = {
    "ernakulam district": "kerala.html",
    "kochi": "kerala.html",
    "fort kochi": "kerala.html",
    "marine drive": "kerala.html",
    "idukki district": "kerala.html",
    "munnar": "kerala.html",
    "thekkady": "kerala.html",
    "vandanmedu": "kerala.html",
    "alappuzha district": "kerala.html",
    "alleppey backwaters": "kerala.html",
    "vembanadu lake": "kerala.html",
    "thiruvananthapuram district": "kerala.html",
    "kovalam beach": "kerala.html",
    "padmanabhaswamy temple": "kerala.html",
    "shankumugham beach": "kerala.html",
    "wayanad district": "kerala.html",
    "edakkal caves": "kerala.html",
    "banasura sagar dam": "kerala.html",
    "kuruva island": "kerala.html",
    # Add Karnataka, Maharashtra places similarly
    "banglore" : "karnataka.html",
    "lalbagh botanical garden" : "karnataka.html",
    "bangalore palace" : "karnataka.html",
    "nandi hills" : "karnataka.html",
    "mysuru" : "karnataka.html",
    "mysore palace" : "karnataka.html",
    "brindavan gardens" : "karnataka.html",
    "coorg" : "karnataka.html",
    "abbey Falls" : "karnataka.html",
    "raja’s seat" : "karnataka.html",
    "udupi" :"karnataka.html",
    "malpe beach" : "karnataka.html",
    "sri krishna temple" : "karnataka.html",
    "hampi" : "karnataka.html",
    "hampi Ruins" : "karnataka.html",
    "virupaksha temple" : "karnataka.html",
    "mumbai" : "maharashtra.html",
    "gateway of india" : "maharashtra.html",
    "marine drive" : "maharashtra.html",
    "elephanta caves" : "maharashtra.html",
    "pune" : "maharashtra.html",
    "shaniwar wada" : "maharashtra.html",
    "aga khan palace" : "maharashtra.html",
    "aurangabad" : "maharashtra.html",
    "ajanta caves" : "maharashtra.html",
    "ellora caves" : "maharashtra.html",
    "nashik" : "maharashtra.html",
    "sula vineyards" : "maharashtra.html",
    "trimbakeshwar temple" : "maharashtra.html",
    "kolhapur" : "maharashtra.html",
    "mahalaxmi temple" : "maharashtra.html",
    "rankala lake" : "maharashtra.html"
}


